### ISSUE TITLE
Glob sources

### ISSUE THREAD

**Issue by sigilante** [assemblycapital/houston#2]
The installation instructions guide one to use `glob-http`:

```
glob-http+['https://bootstrap.urbit.org/glob-0v5.fdf99.nph65.qecq3.ncpjn.q13mb.glob' 0v5.fdf99.nph65.qecq3.ncpjn.q13mb]
```

while the desk default is `glob-ames`.

Is it possible/desirable for you to host an HTTP version as well, kind of like how Quartus hosts Sail and HTML versions of things?

(What I'm trying to do:  build a developer pill with tools including %houston that will work on fake ships, which can't see live %ames.  I can host a copy of course that's set up this way but I think it's \*better* to keep the source at the developer.)

ETA:  to be clear, this isn't mission-critical for what I'm trying to do; I'm just thinking through what our practices should be vis-à-vis developer fake ships and `glob-ames`.

**Comment by gtimoth** [comment]
Here's an http glob you can use for houston v0.0.1
```hoon
glob-http+['https://bwyl.nyc3.digitaloceanspaces.com/houston/houston-0.0.1-0v4.66cdb.r7ita.0shda.8nvaa.affie.glob' 0v4.66cdb.r7ita.0shda.8nvaa.affie]
```

RE: glob practices
I'll probably stick to one distribution of houston. It may change to glob-http with the next release. I hadn't thought about how it affects fakeships.
